
package br.ufes.dcomp.supermercado.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

public class ProdutoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProdutoView.class.getName());

    /**
     * Creates new form ProdutoView
     */
    public ProdutoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblNomeProduto = new javax.swing.JLabel();
        jblPrecoCusto = new javax.swing.JLabel();
        jblCategoriaProduto = new javax.swing.JLabel();
        jblMargemLucro = new javax.swing.JLabel();
        jblPrecoVenda = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        textNomeProduto = new javax.swing.JTextField();
        textPrecoCusto = new javax.swing.JTextField();
        textMargemLucro = new javax.swing.JTextField();
        textPrecoVenda = new javax.swing.JTextField();
        cbTipoCategoriaProduto = new javax.swing.JComboBox<>();
        btnVisualizarHistoricoPrecos = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jblNomeProduto.setText("Nome do Produto:");

        jblPrecoCusto.setText("Preço de custo:");

        jblCategoriaProduto.setText("Categoria do produto:");

        jblMargemLucro.setText("Margem de lucro (%):");

        jblPrecoVenda.setText("Preço de venda:");

        btnSalvar.setText("Salvar");

        btnCancelar.setText("Cancelar");

        btnVisualizarHistoricoPrecos.setText("Visualizar histórico de preços");

        btnEditar.setText("Editar");

        btnFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnVisualizarHistoricoPrecos)
                .addGap(39, 39, 39)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jblCategoriaProduto)
                        .addGap(18, 18, 18)
                        .addComponent(cbTipoCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblNomeProduto)
                            .addComponent(jblPrecoCusto)
                            .addComponent(jblMargemLucro)
                            .addComponent(jblPrecoVenda)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnSalvar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textPrecoVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(textMargemLucro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textPrecoCusto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNomeProduto)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(btnFechar)
                                .addGap(12, 12, 12)))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblNomeProduto)
                    .addComponent(textNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblPrecoCusto)
                    .addComponent(textPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCategoriaProduto)
                    .addComponent(cbTipoCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblMargemLucro)
                    .addComponent(textMargemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblPrecoVenda)
                    .addComponent(textPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnVisualizarHistoricoPrecos)
                    .addComponent(btnEditar)
                    .addComponent(btnFechar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProdutoView().setVisible(true));
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JButton getBtnVisualizarHistoricoPrecos() {
        return btnVisualizarHistoricoPrecos;
    }

    public JComboBox<String> getCbTipoCategoriaProduto() {
        return cbTipoCategoriaProduto;
    }

    public JTextField getTextMargemLucro() {
        return textMargemLucro;
    }

    public JTextField getTextNomeProduto() {
        return textNomeProduto;
    }

    public JTextField getTextPrecoCusto() {
        return textPrecoCusto;
    }

    public JTextField getTextPrecoVenda() {
        return textPrecoVenda;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVisualizarHistoricoPrecos;
    private javax.swing.JComboBox<String> cbTipoCategoriaProduto;
    private javax.swing.JLabel jblCategoriaProduto;
    private javax.swing.JLabel jblMargemLucro;
    private javax.swing.JLabel jblNomeProduto;
    private javax.swing.JLabel jblPrecoCusto;
    private javax.swing.JLabel jblPrecoVenda;
    private javax.swing.JTextField textMargemLucro;
    private javax.swing.JTextField textNomeProduto;
    private javax.swing.JTextField textPrecoCusto;
    private javax.swing.JTextField textPrecoVenda;
    // End of variables declaration//GEN-END:variables
}
