
package br.ufes.dcomp.supermercado.view;

import javax.swing.JMenuItem;

public class TelaPrincipalView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName());

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuIncluirProdutos = new javax.swing.JMenuItem();
        menuBuscarProdutos = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenuItem();
        menuCalcularMargemLucro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Dados");

        menuIncluirProdutos.setText("Incluir produtos");
        menuIncluirProdutos.addActionListener(this::menuIncluirProdutosActionPerformed);
        jMenu1.add(menuIncluirProdutos);

        menuBuscarProdutos.setText("Buscar produtos");
        jMenu1.add(menuBuscarProdutos);

        menuCategorias.setText("Categorias");
        jMenu1.add(menuCategorias);

        menuCalcularMargemLucro.setText("Calcular margem de lucro");
        jMenu1.add(menuCalcularMargemLucro);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIncluirProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIncluirProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuIncluirProdutosActionPerformed

    public JMenuItem getMenuCategorias() {
        return menuCategorias;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipalView().setVisible(true));
    }

    public JMenuItem getMenuBuscarProdutos() {
        return menuBuscarProdutos;
    }
    
    public JMenuItem getMenuCalcularMargem() {
        return menuCalcularMargemLucro;
    }
    
    public JMenuItem getMenuIncluirProdutos() {
        return menuIncluirProdutos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuBuscarProdutos;
    private javax.swing.JMenuItem menuCalcularMargemLucro;
    private javax.swing.JMenuItem menuCategorias;
    private javax.swing.JMenuItem menuIncluirProdutos;
    // End of variables declaration//GEN-END:variables

   
}
