
package br.ufes.dcomp.supermercado.view;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

public class TelaPrincipalView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName());

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        lblNomeUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOperacao = new javax.swing.JMenu();
        jMenuDados = new javax.swing.JMenu();
        menuProdutos = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuEntregadores = new javax.swing.JMenuItem();
        menuTaxasEntrega = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        menuGerenciarUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSair.setText("Sair");

        lblNomeUsuario.setText("Usuário:");

        jMenuOperacao.setText("Operação");
        jMenuBar1.add(jMenuOperacao);

        jMenuDados.setText("Dados");

        menuProdutos.setText("Produtos");
        menuProdutos.addActionListener(this::menuProdutosActionPerformed);
        jMenuDados.add(menuProdutos);

        menuCategorias.setText("Categorias");
        menuCategorias.addActionListener(this::menuCategoriasActionPerformed);
        jMenuDados.add(menuCategorias);

        menuClientes.setText("Clientes");
        jMenuDados.add(menuClientes);

        menuEntregadores.setText("Entregadores");
        jMenuDados.add(menuEntregadores);

        menuTaxasEntrega.setText("Taxas de entrega");
        jMenuDados.add(menuTaxasEntrega);

        jMenuBar1.add(jMenuDados);

        jMenuUsuarios.setText("Usuários");

        menuGerenciarUsuarios.setText("Gerenciar");
        jMenuUsuarios.add(menuGerenciarUsuarios);

        jMenuBar1.add(jMenuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(436, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNomeUsuario)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblNomeUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProdutosActionPerformed

    private void menuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCategoriasActionPerformed

    public javax.swing.JButton getBtnSair() {
        return btnSair;
    }

    public JLabel getLblNomeUsuario() {
        return lblNomeUsuario;
    }

    public JMenu getMenuOperacao() {
        return jMenuOperacao;
    }

    public JMenu getMenuDados() {
        return jMenuDados;
    }

    public JMenu getMenuUsuarios() {
        return jMenuUsuarios;
    }
    
    public JMenuItem getMenuGerenciarUsuarios() {
        return menuGerenciarUsuarios;
    }

    public JMenuItem getMenuProdutos() {
        return menuProdutos;
    }

    public JMenuItem getMenuCategorias() {
        return menuCategorias;
    }

    public JMenuItem getMenuClientes() {
        return menuClientes;
    }

    public JMenuItem getMenuEntregadores() {
        return menuEntregadores;
    }

    public JMenuItem getMenuTaxasEntrega() {
        return menuTaxasEntrega;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDados;
    private javax.swing.JMenu jMenuOperacao;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JMenuItem menuCategorias;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuEntregadores;
    private javax.swing.JMenuItem menuGerenciarUsuarios;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenuItem menuTaxasEntrega;
    // End of variables declaration//GEN-END:variables

   
}
